In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os

In [2]:
import nltk

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('omw-1.4')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package omw-1.4 to /Users/mehdi/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/mehdi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /Users/mehdi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/mehdi/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

{'<url>',
 '<user>',
 'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    text = text.lower()
    text = word_tokenize(text)
    text = [lemmatizer.lemmatize(word) for word in text if word not in stop_words]
    text = ' '.join(text)
    return text

In [4]:
pathv = "./data/"
# load the data, read the txt file and convert it to a csv file
df_negative = pd.read_csv(pathv + "train_neg.txt", sep = "\t", header = None)
df_negative.columns = ["text"]
#
df_negative['text'] = df_negative['text'].apply(lemmatize_text)

df_positive = pd.read_csv(pathv + "train_pos.txt", sep = "\t", header = None)
df_positive.columns = ["text"]
#
df_positive['text'] = df_positive['text'].apply(lemmatize_text)

In [5]:
# display df_nagative and its length
print(len(df_negative))
df_negative.head(5)

99068

                                                text
0  vinco tresorpack 6 ( difficulty 10 10 object :...
1    glad dot taks tomorrow ! ! # thankful # startho
2  1-3 v celtic regular season = fucked play playoff
3   < user > could actually kill girl 'm sorry ! ! !
4  < user > < user > < user > find hard believe i...

In [6]:
# display Positive and its length
print(len(df_positive))
df_positive.head(5)

97902

                                                text
0  < user > dunno justin read mention . justin go...
1  logic dumb , wo n't even crop name photo . tsk...
2  < user > put casper box ! looved battle ! # cr...
3  < user > < user > thanks sir > > n't trip lil ...
4  visiting brother tmr bestest birthday gift eve...

In [7]:
# count the occurence of each word in the text
from collections import Counter
word_count = Counter()
for text in df_positive["text"].values:
    for word in text.split():
        word_count[word] += 1
df_word_count_positive = pd.DataFrame.from_dict(word_count, orient = "index")
df_word_count_positive.columns = ["count_positive"]
df_word_count = df_word_count_positive.sort_values(by = "count_positive", ascending = False)

In [8]:
# count the occurence of each word in the text
word_count = Counter()
for text in df_negative["text"].values:
    for word in text.split():
        word_count[word] += 1
df_word_count_negative = pd.DataFrame.from_dict(word_count, orient = "index")
df_word_count_negative.columns = ["count_negative"]
df_word_count_negative = df_word_count_negative.sort_values(by = "count_negative", ascending = False)

In [9]:
# combine the two dataframes with the index as the word
df_word_count = pd.concat([df_word_count_negative, df_word_count_positive], axis = 1)
df_word_count = df_word_count.fillna(0)

In [10]:
df_word_count ["diff"]= (df_word_count["count_positive"] - df_word_count["count_negative"])
df_word_count = df_word_count.sort_values(by = "diff", ascending = False)
df_word_count.head(30)

           count_negative  count_positive     diff
user              46378.0         81663.0  35285.0
!                 30183.0         52891.0  22708.0
<                 83245.0         95026.0  11781.0
>                 82054.0         93149.0  11095.0
love               2782.0          8932.0   6150.0
#                 12094.0         17238.0   5144.0
follow             1581.0          5646.0   4065.0
thanks              583.0          4609.0   4026.0
?                 11294.0         15124.0   3830.0
good               1984.0          5731.0   3747.0
lol                2350.0          5419.0   3069.0
thank               262.0          3100.0   2838.0
rt                 4723.0          7456.0   2733.0
haha               1079.0          3416.0   2337.0
beautiful           368.0          2572.0   2204.0
'll                1484.0          3606.0   2122.0
)                  6751.0          8676.0   1925.0
fan                 475.0          2400.0   1925.0
happy               632.0          2497.0   1865.0
u                  4170.0          5922.0   1752.0
x                  2427.0          4133.0   1706.0
day                2965.0          4670.0   1705.0
hey                 353.0          1701.0   1348.0
know               3342.0          4679.0   1337.0
please             2464.0          3796.0   1332.0
're                1427.0          2668.0   1241.0
xx                  740.0          1968.0   1228.0
birthday            362.0          1539.0   1177.0
great               718.0          1794.0   1076.0
yes                 659.0          1730.0   1071.0

In [11]:
df_word_count ["diff"]= (df_word_count["count_positive"] - df_word_count["count_negative"])
df_word_count = df_word_count.sort_values(by = "diff", ascending = True)
df_word_count.head(30)

           count_negative  count_positive     diff
(                 44330.0          2826.0 -41504.0
...               33139.0          7830.0 -25309.0
url               34311.0          9331.0 -24980.0
-                 12925.0          3777.0  -9148.0
frame              7977.0            12.0  -7965.0
:                 12484.0          6188.0  -6296.0
,                 32525.0         27167.0  -5358.0
/                  7464.0          2287.0  -5177.0
n't               11848.0          7637.0  -4211.0
``                 9801.0          6206.0  -3595.0
paperback          3517.0             3.0  -3514.0
pack               2562.0            61.0  -2501.0
miss               3321.0           917.0  -2404.0
black              2567.0           203.0  -2364.0
complete           2430.0            69.0  -2361.0
wide               2099.0            35.0  -2064.0
poster             2077.0            45.0  -2032.0
2                  3536.0          1526.0  -2010.0
custom             1986.0             8.0  -1978.0
sad                2005.0           140.0  -1865.0
picture            2397.0           541.0  -1856.0
edition            1762.0            21.0  -1741.0
wish               2591.0           910.0  -1681.0
1                  2468.0           942.0  -1526.0
hate               1832.0           385.0  -1447.0
hardcover          1339.0             0.0  -1339.0
ca                 3176.0          1874.0  -1302.0
book               1469.0           248.0  -1221.0
cry                1392.0           210.0  -1182.0
6                  1336.0           207.0  -1129.0